import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import {
  MEDIEVAL_CHARACTER_RECIPES,
  buildMedievalCharacterKitManifest,
  generateMedievalCharacterKit,
  generateMedievalCharacterObj,
} from "../src/medieval-character-kit.js";

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

test("medieval character kit exposes the first three gameplay archetypes", () => {
  assert.deepEqual(Object.keys(MEDIEVAL_CHARACTER_RECIPES), ["soldier", "archer", "knight"]);
  assert(MEDIEVAL_CHARACTER_RECIPES.soldier.parts.some((part) => part.name === "shield"));
  assert(MEDIEVAL_CHARACTER_RECIPES.soldier.parts.some((part) => part.name === "spear"));
  assert(MEDIEVAL_CHARACTER_RECIPES.archer.parts.some((part) => part.name === "bow-stave"));
  assert(MEDIEVAL_CHARACTER_RECIPES.archer.parts.some((part) => part.name === "quiver"));
  assert(MEDIEVAL_CHARACTER_RECIPES.knight.parts.some((part) => part.name === "helmet"));
  assert(MEDIEVAL_CHARACTER_RECIPES.knight.parts.some((part) => part.name === "sword"));
});

test("medieval character OBJ generation is deterministic and keeps semantic part groups", () => {
  for (const archetype of ["soldier", "archer", "knight"]) {
    const first = generateMedievalCharacterObj(archetype);
    const second = generateMedievalCharacterObj(archetype);
    assert.equal(Buffer.compare(first.bytes, second.bytes), 0);
    assert.equal(first.coordinateSystem, "right-handed-y-up");
    assert.equal(first.unit, "millimeter");
    assert.equal(first.consumerScaleToMeters, "0.001");
    assert.equal(first.bounds.min[1], "0");
    assert(first.vertexCount > 0);
    assert(first.triangleCount > 0);
    assert.match(first.bytes.toString("utf8"), new RegExp(`^# asset-tooling medieval character kit OBJ v1\\n# recipe-version 1\\no medieval-${archetype}\\n`));
    for (const partName of first.partNames) {
      assert.match(first.bytes.toString("utf8"), new RegExp(`\\ng ${partName}\\n`));
    }
  }
});

test("medieval archetypes remain distinct low-poly meshes", () => {
  const kit = generateMedievalCharacterKit();
  assert.deepEqual(kit.map((asset) => asset.archetype), ["soldier", "archer", "knight"]);
  assert.equal(new Set(kit.map((asset) => sha256(asset.bytes))).size, 3);
  assert.equal(generateMedievalCharacterObj("soldier").bounds.max[1], "1900");
  assert.equal(generateMedievalCharacterObj("archer").bounds.max[1], "1760");
  assert.equal(generateMedievalCharacterObj("knight").bounds.max[1], "1790");
});

test("medieval character manifest binds exact generated bytes and geometry evidence", () => {
  const kit = generateMedievalCharacterKit();
  const manifest = buildMedievalCharacterKitManifest();
  assert.equal(manifest.schemaVersion, 1);
  assert.equal(manifest.recipeVersion, "1");
  assert.equal(manifest.coordinateSystem, "right-handed-y-up");
  assert.equal(manifest.unit, "millimeter");
  assert.equal(manifest.consumerScaleToMeters, "0.001");
  assert.deepEqual(manifest.assets.map((asset) => asset.id), ["medieval.soldier", "medieval.archer", "medieval.knight"]);
  for (const [index, entry] of manifest.assets.entries()) {
    const generated = kit[index];
    assert.equal(entry.fileName, `${generated.archetype}.obj`);
    assert.equal(entry.mediaType, "model/obj");
    assert.equal(entry.sha256, sha256(generated.bytes));
    assert.equal(entry.byteLength, generated.bytes.length);
    assert.equal(entry.vertexCount, generated.vertexCount);
    assert.equal(entry.triangleCount, generated.triangleCount);
    assert.deepEqual(entry.bounds, generated.bounds);
    assert.deepEqual(entry.parts, generated.partNames);
  }
});

test("medieval character generation rejects unknown archetypes", () => {
  assert.throws(() => generateMedievalCharacterObj("horse-archer"), /unknown medieval character archetype/);
});
