import test from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { generateAsset } from "../src/core.js";
import { prepareProcessingHandoff } from "../src/processing-handoff.js";
import { sha256Bytes } from "../src/hash.js";

async function workspace() {
  const root = await mkdtemp(path.join(os.tmpdir(), "asset-tooling-processing-handoff-"));
  const source = Buffer.from("generated processing source\n", "utf8");
  await writeFile(path.join(root, "source.txt"), source);
  const spec = {
    schemaVersion: 1,
    assetId: "test.processing-handoff",
    generator: { id: "builtin.copy", version: "1" },
    randomness: { mode: "none" },
    inputs: {
      source: {
        path: "source.txt",
        sha256: sha256Bytes(source),
      },
    },
    models: {},
    parameters: {},
    output: { path: ".asset-tooling/generated.bin" },
    reproducibility: { expected: "exact" },
  };
  const specPath = path.join(root, "asset.json");
  await writeFile(specPath, `${JSON.stringify(spec, null, 2)}\n`, "utf8");
  return { root, specPath };
}

test("processing handoff uses generation output SHA as the processing input SHA", async () => {
  const { specPath } = await workspace();
  const generation = await generateAsset(specPath);
  const handoff = await prepareProcessingHandoff(specPath, {
    mediaType: "application/octet-stream",
  });

  assert.equal(handoff.schemaVersion, 1);
  assert.equal(handoff.input.sha256, generation.outputSha256);
  assert.equal(handoff.input.mediaType, "application/octet-stream");
  assert.equal(handoff.lineage.kind, "generation-receipt");
  assert.equal(handoff.lineage.assetId, "test.processing-handoff");
  assert.match(handoff.lineage.generationReceiptSha256, /^[0-9a-f]{64}$/);
});

test("processing handoff fails closed when accepted generated bytes drift", async () => {
  const { specPath, root } = await workspace();
  await generateAsset(specPath);
  await writeFile(path.join(root, ".asset-tooling", "generated.bin"), "tampered\n");

  await assert.rejects(
    () => prepareProcessingHandoff(specPath, { mediaType: "application/octet-stream" }),
    /generation output hash mismatch/,
  );
});

test("processing handoff fails closed when receipt/spec parameters drift", async () => {
  const { specPath, root } = await workspace();
  const generation = await generateAsset(specPath);
  const receiptPath = path.join(root, generation.receiptPath);
  const receipt = JSON.parse(await readFile(receiptPath, "utf8"));
  receipt.parameters = { fabricated: true };
  await writeFile(receiptPath, `${JSON.stringify(receipt, null, 2)}\n`, "utf8");

  await assert.rejects(
    () => prepareProcessingHandoff(specPath, { mediaType: "application/octet-stream" }),
    /parametersSha256 does not match receipt\.parameters/,
  );
});

test("handoff input is structurally identical to processing receipt v2 artifact input", async () => {
  const { specPath } = await workspace();
  await generateAsset(specPath);
  const handoff = await prepareProcessingHandoff(specPath, { mediaType: "model/gltf-binary" });
  const processingSchema = JSON.parse(
    await readFile(new URL("../schemas/processing-receipt-v2.schema.json", import.meta.url), "utf8"),
  );

  assert.deepEqual(Object.keys(handoff.input).sort(), ["mediaType", "sha256"]);
  assert.deepEqual(processingSchema.$defs.artifact.required, ["sha256", "mediaType"]);
  assert.equal(processingSchema.$defs.artifact.additionalProperties, false);
});

test("processing handoff schema requires portable generation receipt paths", async () => {
  const schema = JSON.parse(
    await readFile(new URL("../schemas/processing-handoff-v1.schema.json", import.meta.url), "utf8"),
  );
  const portablePath = new RegExp(schema.$defs.portablePath.pattern);

  assert.equal(portablePath.test(".asset-tooling/generated.bin.receipt.json"), true);
  for (const candidate of [
    "/tmp/receipt.json",
    "../receipt.json",
    "receipts\\x.json",
    "C:/receipts/x.json",
    "D:receipt.json",
    "receipts//x.json",
  ]) {
    assert.equal(portablePath.test(candidate), false, candidate);
  }
  assert.equal(
    schema.$defs.generationLineage.properties.generationReceiptPath.$ref,
    "#/$defs/portablePath",
  );
});
