import test from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { generateAsset, validateSpec, verifyAsset } from "../src/core.js";

const EXPECTED_SHA256 = "59160909e6eac80d18bb58cd8a72a308df2c52c4ed866288bc73f48996f912a5";

function proceduralSpec(seed = "42") {
  return {
    schemaVersion: 1,
    assetId: "test.procedural-svg-scatter",
    generator: { id: "builtin.procedural.svg-scatter", version: "1" },
    randomness: { mode: "seeded", seed },
    inputs: {},
    models: {},
    parameters: {
      width: 96,
      height: 64,
      count: 8,
      minRadius: 2,
      maxRadius: 6,
      background: "#101418",
      palette: ["#ffcc00", "#3366ff", "#33aa66"],
    },
    output: { path: ".asset-tooling/scatter.svg" },
    reproducibility: { expected: "exact" },
  };
}

async function writeWorkspace(seed = "42") {
  const root = await mkdtemp(path.join(os.tmpdir(), "asset-tooling-procedural-"));
  const specPath = path.join(root, "asset.json");
  await writeFile(specPath, `${JSON.stringify(proceduralSpec(seed), null, 2)}\n`);
  return { root, specPath };
}

test("procedural SVG backend validates a seeded model-free spec", async () => {
  const { specPath } = await writeWorkspace();
  const result = await validateSpec(specPath);
  assert.equal(result.status, "valid");
});

test("procedural SVG generation has a fixed cross-run golden hash", async () => {
  const { specPath, root } = await writeWorkspace();
  const first = await generateAsset(specPath);
  const second = await generateAsset(specPath);

  assert.equal(first.outputSha256, EXPECTED_SHA256);
  assert.equal(second.outputSha256, EXPECTED_SHA256);
  assert.equal(first.status, "changed");
  assert.equal(second.status, "unchanged");
  const svg = await readFile(path.join(root, ".asset-tooling", "scatter.svg"), "utf8");
  assert.equal((svg.match(/<circle /g) ?? []).length, 8);
});

test("procedural SVG replay earns exact reproducibility", async () => {
  const { specPath } = await writeWorkspace();
  await generateAsset(specPath);
  const report = await verifyAsset(specPath);
  assert.equal(report.status, "exact");
  assert.equal(report.checks.regeneratedOutputMatchesReceipt, true);
});

test("procedural SVG seed changes generated bytes", async () => {
  const first = await writeWorkspace("42");
  const second = await writeWorkspace("43");
  const firstResult = await generateAsset(first.specPath);
  const secondResult = await generateAsset(second.specPath);
  assert.notEqual(firstResult.outputSha256, secondResult.outputSha256);
});

test("procedural SVG backend rejects ambient dependencies and unknown parameters", async () => {
  const { specPath } = await writeWorkspace();
  const spec = proceduralSpec();
  spec.parameters.untracked = true;
  await writeFile(specPath, `${JSON.stringify(spec, null, 2)}\n`);
  await assert.rejects(() => validateSpec(specPath), /does not accept parameter 'untracked'/);
});
